### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/currency#139]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] currency_old_rate_notify - By @alexis-via - #165
- [x] currency_rate_update - By @AEstLo - #141
- [x] currency_rate_update_xe - By @mpascuall - #193

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by AEstLo** [comment]
currency_rate_update: https://github.com/OCA/currency/pull/141

**Comment by BT-anieto** [comment]
I'm missing the module **base_currency_iso_4217**

**Comment by mpascuall** [comment]
Missing res_currency_rate_provider_XE. I'd like to migrate it

**Comment by pedrobaeza** [comment]
Go ahead and when ready, it will be referenced here launching a bot command.
